// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaYMYHyZ7MbDBJtdRLinBtMNooFF76ecc',
    appId: '1:1084354067592:web:9c3f2369e1c82e0d4db33d',
    messagingSenderId: '1084354067592',
    projectId: 'auto-shop-b91b2',
    authDomain: 'auto-shop-b91b2.firebaseapp.com',
    storageBucket: 'auto-shop-b91b2.appspot.com',
    measurementId: 'G-CYL5TGTCM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIze8QFHtQFjlLov1icQRvZ-KEfAApblo',
    appId: '1:1084354067592:android:237c84490e8778234db33d',
    messagingSenderId: '1084354067592',
    projectId: 'auto-shop-b91b2',
    storageBucket: 'auto-shop-b91b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIK3qD4zMts_-JoI-TmBHX7Rv13Lm_wrs',
    appId: '1:1084354067592:ios:8d438c690c8cb6a44db33d',
    messagingSenderId: '1084354067592',
    projectId: 'auto-shop-b91b2',
    storageBucket: 'auto-shop-b91b2.appspot.com',
    iosClientId: '1084354067592-rf1if5tuq9cjc3i1clkvollgmtlkj017.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIK3qD4zMts_-JoI-TmBHX7Rv13Lm_wrs',
    appId: '1:1084354067592:ios:8d438c690c8cb6a44db33d',
    messagingSenderId: '1084354067592',
    projectId: 'auto-shop-b91b2',
    storageBucket: 'auto-shop-b91b2.appspot.com',
    iosClientId: '1084354067592-rf1if5tuq9cjc3i1clkvollgmtlkj017.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoShop',
  );
}
